name: dotnet-build
description: 'Build dotnet project'

on:
  workflow_call:
    inputs:
      dotnet_version:
        description: 'Required dotnet version e.g. "7.x"'
        required: true
      project_path:
        description: 'Path to project e.g. "./my-proj.csproj"'
        required: false
        default: '.'

runs:
  steps:
    - run: echo "BUILD_OUTPUT_PATH=./output" >> $GITHUB_ENV
      shell: bash

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Restore dependencies
      shell: bash
      run: dotnet restore ${{ inputs.project_path }}

    - name: Build
      shell: bash
      run: dotnet build ${{ inputs.project_path }} --configuration Release --no-restore --output ${{ env.BUILD_OUTPUT_PATH }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-package
        path: ${{ env.BUILD_OUTPUT_PATH }}
        if-no-files-found: error
        retention-days: 1