name: dotnet-build
description: 'Test dotnet project'

inputs:
  dotnet_version:
    description: 'Required dotnet version e.g. "7.x"'
    required: true
  path:
    description: 'Path to project or solution e.g. "./my-solution.sln"'
    required: false
    default: '.'
  app_artifact_name:
    description: 'Name of the artifact containing the application package'
    required: false
    default: 'app-package'

runs:
  using: "composite"
  steps:
    - run: echo "APP_PACKAGE_PATH=./output" >> $GITHUB_ENV
      shell: bash

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Restore dependencies
      shell: bash
      run: dotnet restore ${{ inputs.path }}

    - name: Build
      shell: bash
      run: dotnet build ${{ inputs.path }} --configuration Release --no-restore

    - name: Test
      shell: bash
      run: dotnet test ${{ inputs.path }} --configuration Release --no-build --no-restore