# 
# Purpose: Build dotnet source code
#

name: dotnet-build

on:
  workflow_call:
    inputs:
      dotnet_version:
        type: string
        description: 'Required dotnet version e.g. "7.x"'
        required: true
      project_path:
        type: string
        description: 'Path to project e.g. "./my-proj.csproj"'
        required: true
      os_platform:
        type: string
        description: 'Operating system platform e.g. "windows-latest". See https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#choosing-github-hosted-runners.'
        required: false
        default: 'ubuntu-latest'
      app_artifact_name:
        type: string
        description: 'Name of the uploaded build artifact'
        required: false
        default: 'app-package'

env:
  BUILD_OUTPUT_PATH: './output'

jobs:
  build:
    runs-on: ${{ inputs.os_platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Restore dependencies
        shell: bash
        run: dotnet restore ${{ inputs.project_path }}

      - name: Build
        shell: bash
        run: dotnet build ${{ inputs.project_path }} --configuration Release --no-restore --output ${{ env.BUILD_OUTPUT_PATH }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.app_artifact_name }}
          path: ${{ env.BUILD_OUTPUT_PATH }}
          if-no-files-found: error
          retention-days: 1