# 
# Purpose: Run dotnet tests
#

name: dotnet-test

on:
  workflow_call:
    inputs:
      dotnet_version:
        type: string
        description: 'Required dotnet version e.g. "7.x"'
        required: true
      path:
        type: string
        description: 'Path to project or solution e.g. "./my-solution.sln"'
        required: false
        default: '.'
      os_platform:
        type: string
        description: 'Operating system platform e.g. "windows-latest". See https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#choosing-github-hosted-runners.'
        required: false
        default: 'ubuntu-latest'

jobs:
  run-tests:
    runs-on: ${{ inputs.os_platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Restore dependencies
        shell: bash
        run: dotnet restore ${{ inputs.path }}

      - name: Build
        shell: bash
        run: dotnet build ${{ inputs.path }} --configuration Release --no-restore

      - name: Test
        shell: bash
        run: dotnet test ${{ inputs.path }} --configuration Release --no-build --no-restore