# 
# Purpose: Build source code using npm
#

name: npm-build

on:
  workflow_call:
    inputs:
      node_version:
        type: string
        description: 'Required node version e.g. "16"'
        required: true
      path:
        type: string
        description: 'Path to source code e.g. "src"'
        required: true
      os_platform:
        type: string
        description: 'Operating system platform e.g. "windows-latest". See https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#choosing-github-hosted-runners.'
        required: false
        default: 'ubuntu-latest'
      # app_artifact_name:
      #   type: string
      #   description: 'Name of the uploaded build artifact'
      #   required: false
      #   default: 'app-package'

env:
  BUILD_OUTPUT_PATH: './output'

jobs:
  build:
    runs-on: ${{ inputs.os_platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Install node'
        uses: actions/setup-node@v3
        with:
         node-version: ${{ inputs.node_version }}

      - name: 'Fetch dependencies'
        run: npm ci

      - name: 'Build'
        run: npm run build
        working-directory: ${{ inputs.path }}

      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ inputs.app_artifact_name }}
      #     path: ${{ env.BUILD_OUTPUT_PATH }}
      #     if-no-files-found: error
      #     retention-days: 1